// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huyumzlevlcxsnvbtcsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1eXVtemxldmxjeHNudmJ0Y3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzA2NjYsImV4cCI6MjA2NTQ0NjY2Nn0.UsQ_zUjFSvdi8fTNIH4p2U8IxWqrsc7Hlic5qB3hetE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);